.. note:: The Images API v1 has been DEPRECATED in the Newton release.  The
    migration path is to use the `Images API v2
    <http://developer.openstack.org/api-ref/image/v2/>`_ instead of version 1
    of the API.  The Images API v1 will ultimately be removed, following the
    `OpenStack standard deprecation policy
    <https://governance.openstack.org/reference/tags/assert_follows-standard-deprecation.html>`_.
